[versions]
## plugins
agp = "8.10.0"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.25"

coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeCompiler = "1.5.15"
composeBom = "2025.05.00"
jsoup = "1.20.1"
appcompat = "1.7.0"
material = "1.12.0"

## dependency injection
hilt = "2.56.2"
## Data
rssparserVersion = "6.0.10" #release 27 Feb 2025

## Test
jupiterVersion = "5.12.2" #release 11 Apr 2025
mockkVersion = "1.14.0" #release 09 Apr 2025
mockWebServerVersion = "4.12.0"  #17 Oct 2023 #last stable release, 5.x.x still in alpha as of 07 may 2025
coroutinesTestVersion = "1.10.2" #04 Apr 2025

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

## dependency injection
# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "composeCompiler" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

##  data
rss-parser = { group = "com.prof18.rssparser", name = "rssparser", version.ref = "rssparserVersion" }


## test
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiterVersion" }
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiterVersion" }
jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiterVersion" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockWebServerVersion" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTestVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
